services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Tourze\Symfony\AOP\Aspect\:
    resource: '../../Aspect/'
  Tourze\Symfony\AOP\Service\:
    resource: '../../Service/'

  sf-aop.file-locator:
    class: ProxyManager\FileLocator\FileLocator
    arguments: [ '%kernel.cache_dir%' ]
  sf-aop.generator-strategy:
    class: ProxyManager\GeneratorStrategy\FileWriterGeneratorStrategy
    arguments: [ '@sf-aop.file-locator' ]
  sf-aop.configuration:
    class: ProxyManager\Configuration
    calls:
      - [ 'setGeneratorStrategy', [ '@sf-aop.generator-strategy' ] ]
      - [ 'setProxiesTargetDir', [ '%kernel.cache_dir%' ] ]
      - [ 'setProxiesNamespace', [ 'AopProxy' ] ]
  sf-aop.value-holder-proxy-manager:
    class: ProxyManager\Factory\AccessInterceptorValueHolderFactory
    arguments: [ '@sf-aop.configuration' ]
